# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  url_launcher: ^6.2.5
  google_fonts: ^6.2.0
  analyzer: ^6.2.0
  intl: ^0.19.0
  nylo_framework: ^5.24.6
  pretty_dio_logger: ^1.3.1
  # dash_chat_2: ^0.0.20
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.6
  eva_icons_flutter: ^3.1.0
  google_sign_in: ^6.2.1
  gap: ^3.0.1
  google_nav_bar: ^5.0.6
  mask_text_input_formatter: ^2.9.0
  flutter_easyloading: ^3.0.5
  skeletonizer: ^1.1.2+1
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  popover: ^0.3.0+1
  dash_chat_2:
    path: ../Dash-Chat-2
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6
  modal_bottom_sheet: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  #  flutter_lints: ^3.0.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
