// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxVRdZX1jqFqMCJRHmCv_iNvCMD-16LA',
    appId: '1:446706638139:android:68d7164b42e019ce80ab1e',
    messagingSenderId: '446706638139',
    projectId: 'bengkel-412815',
    storageBucket: 'bengkel-412815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXers69GlsE0DGLOeITHVdGHa9raoS3UY',
    appId: '1:446706638139:ios:8df8b46dab9d944d80ab1e',
    messagingSenderId: '446706638139',
    projectId: 'bengkel-412815',
    storageBucket: 'bengkel-412815.appspot.com',
    androidClientId: '446706638139-epjtgjbfnm4tggnts5gk45qd9hfetb2g.apps.googleusercontent.com',
    iosClientId: '446706638139-ig39aaai6k8pv4sgb0hldkdi2qtet6cb.apps.googleusercontent.com',
    iosBundleId: 'com.nylo.ios',
  );
}
